var userName;
// let userName : Array<string>; // this is also another way to declare the array in typescript
userName = ['azad', 'rakib', 'babul', 'abul'];
userName.sort();
console.log(userName);
var multipleType;
multipleType = [1, 'azad', 'sadiya'];
console.log(multipleType);
var users;
users = ['anis', 'rabu', 'pinky'];
users.sort();
console.log(users);
users.push('limon');
console.log(users);
users.pop();
console.log(users);
users.unshift('milton');
console.log(users);
users.shift();
console.log(users);
